### ISSUE TITLE
Dependency on Catel

### ISSUE THREAD

**Issue by JobaDiniz** [WildGums/Orc.Wizard#15]
Your control looks great, but it depends on Catel, which is bad.
I mean, there are other MVVM frameworks and turns out each project uses a different one, for example, I'm using Caliburn.Micro.

It would be great if your lib drop this dependency and let the users choose which MVVM framework fits best.

**Comment by GeertvanHorrik** [comment]
Hi @JobaDiniz,

Thanks for your comments. This might sound harsh, but I want to be honest for your expectations. We will never drop the dependency since we are the authors of Catel as well. We will not work around limitations of other stuff in order to make this work for other frameworks.

The libraries we write are for our own usage. We provide them for free to the community, but this doesn't mean we write it *for* the community. So we will implement whatever we need for our own good, and everyone is free to use and/or fork.
