### ISSUE TITLE
WizardWindow derives from a XAML generated class, cannot be main window

### ISSUE THREAD

**Issue by Kilazur** [WildGums/Orc.Wizard#19]
### Steps to reproduce

1. Create a new Catel project
2. Add Orc.Wizard as a reference, and its dependencies
3. Modify MainWindow.XAML to be a Orc.Wizard.View.WizardWindow instead of a Window
4. Try to generate

Platform:
.NET version: 4.0

### Expected behaviour

Having a WizardWindow as the main window for the program.

### Actual behaviour

The program cannot compile, producing an error reading " 'Orc.Wizard.Views.WizardWindow' cannot be the root of a XAML file because it was defined using XAML ".
See also: https://support.microsoft.com/en-us/help/957231/wpf-build-error-mc6017-when-you-define-a-class-that-derives-from-a-xam

**Comment by GeertvanHorrik** [comment]
Can you also upload the repro? Then we don't have to guess stuff to do for step 3. Thanks!

**Comment by Kilazur** [comment]
Here's the repro:

[Orc_WizardWindow.zip](https://github.com/WildGums/Orc.Wizard/files/1506128/Orc_WizardWindow.zip)

**Comment by alexfdezsauco** [comment]
Sorry for the delayed response.

You are trying to use the wizard window in a wrong way and as you read  'Orc.Wizard.Views.WizardWindow' cannot be the root of a XAML file because it was defined using XAML.

In order to use Orc.Wizard correctly you should know:

1) The wizard window is the host for a user controls that acts as wizard pages. 
2) The wizard should be used via Wizard service.

So, if you want to create a wizard app (where the "MainWindow is a wizard") take a look into the attached demo wizard app. 

[Orc_WizardWindow.zip](https://github.com/WildGums/Orc.Wizard/files/1582568/Orc_WizardWindow.zip)

**Comment by GeertvanHorrik** [comment]
Closing assuming the answer by @alexfdezsauco helped you out. If not, feel free to re-open.
